use_nerdfont = true
album_column = true
volnorm = true
notify = false
backend = "pulseaudio"


[theme]
background = "#000000"
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "light green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"
search_match = "light red"

[keybindings]
"Shift+g" = "move bottom"
"Shift+l" = "focus library"
"Shift+q" = "focus queue"
"g" = "move top"
